#!/usr/bin/env python

import sys

a="salam"

def func_to_test(arg1, arg2):
    print("First argument will be printed: "+arg1)
    print("Second argument will be printed: "+arg2)

func_to_test("Salam", "saqol")
func_to_test(sys.argv[1], sys.argv[2])

def newfunc(farg1, sarg1):
    print(farg1[0:3])
    print(sarg1[0:4])

newfunc(sys.argv[2], sys.argv[1])


